# Generated by Django 4.2.1 on 2024-04-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mysite',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='mysite',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='mysite',
            index=models.Index(fields=['-time_create'], name='mysite_mysi_time_cr_d5f93d_idx'),
        ),
    ]
