# Generated by Django 4.2.1 on 2024-04-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_mysite_options_mysite_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysite',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
