# Generated by Django 4.2.1 on 2024-04-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_mysite_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysite',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
