# Generated by Django 4.2.1 on 2024-06-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_rename_name_isbn_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysite',
            name='view_count',
            field=models.IntegerField(blank='True', default=0),
        ),
    ]
